export const MOVIE_LOADING = 'MOVIE_LOADING';
export const MOVIE_LIST_SET = 'MOVIE_LIST_SET';
export const MOVIE_SEARCH_KEYWORD_ADD = 'MOVIE_SEARCH_KEYWORD_ADD';
export const MOVIE_SEARCH_KEYWORD_DEL = 'MOVIE_SEARCH_KEYWORD_DEL';
